# Albert Lee Homework 1

# Problem #1

### a.	(4 points) Choose a tradeable instrument to express your view.

#### FX – USD against AUD, CAD, CHF, CNY, EUR, GBP, JPY, NZD

### b.	(4 points) Choose explanatory variables (feature)

#### 1)	News in global economic events, monetary policy changes, and politics  (Forex Calendar)
#### 2)	Trend in historical exchange rates

### c.	(4 points) Define strategy parameters.

#### 1)	News variable need to be calibrated daily since news agencies publish slightly different views on or results of the same event every day so do economists.
#### 2)	Trend in historical exchange rates will be used to identify a general shape or patterns of a long-term curve, so it will be calibrated quarterly (3 months)

### d.	(4 points) Data/Feature engineering.

#### 1)	News variable must be checked manually and evaluated by a trader (myself), and the trader will adjust the expected gain/loss of the account, according to the trader’s own score matrix (supervised learning classification -> apply scores within each labeled class -> Sum of Regression applied to classified variables in each class) that can be managed with MS Excel spreadsheet or Python. Historical rates of USD against other major currencies can be obtained from Yahoo Finance
#### 2)	Significantly relevant types (classes) of news will be continuously added to the trader’s score matrix
#### 3) Possible features: Monetary policy change (positive/negative), political event (positive/negative), Major anouncements from large, global companies (postiive/negative),

### e.	(4 points) Choose a model

#### 1)	Classification (what types of news? (Monetary Policy, Sudden oil price changes and so on / Negative or positive?)
#### 2)	After classification, apply regression model with historical news and the historical FX rates and sum up the expected changes in USD and add the sum to the value predicted by historical prices (trend)

### f.	(5 points) Describe how you will calibrate/tune/learn the parameters, including the data time frame.

#### 1)	For classification model, the trader needs to add more labels if there are usual but expected to remain influential in the future so that the model can consider that feature.
#### 2)	For a regression model for each classified class, it will be calibrated monthly while, for a regression model for a historical data will be calibrated every 3 month
#### 3)	All models will be learned with data (event / rates ) for the last 3 months

### g.	(5 points) Describe how you will test the results, including the data time frame.  Include specific metrics.

#### 1)	Compare the expected FX rates with predicted ones
#### 2)	The goal is to have each regression model reach above 90% R-squared

In [1]:
import numpy as np
import pandas as pd
from sklearn.covariance import LedoitWolf, OAS

# Problem #2

### a Write 2 sentences on your understanding of the methodology.

#### Covariance matrix can have exteremly large estimation errors such that incorrectly measured high correlation between assets may lead portfolio managers to assign ill-optimized weights to the assets. OAS, LW methods find covariance estimators that remove risky extrema in covariance measure.

### b.	(4 points) Create a 1000x20 matrix “X” from random normal dist.  Create new matrix X* that is a copy of X.  Replace last two columns with first column with 1e-4 random normal noise added to it.

In [2]:
seed_1 = np.random.seed(1)

In [3]:
X = pd.DataFrame(np.random.randn(1000, 20))

In [4]:
print('X')
X.head()

X

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,1.624345,-0.611756,-0.528172,-1.072969,0.865408,-2.301539,1.744812,-0.761207,0.319039,-0.249370,1.462108,-2.060141,-0.322417,-0.384054,1.133769,-1.099891,-0.172428,-0.877858,0.042214,0.582815
1,-1.100619,1.144724,0.901591,0.502494,0.900856,-0.683728,-0.122890,-0.935769,-0.267888,0.530355,-0.691661,-0.396754,-0.687173,-0.845206,-0.671246,-0.012665,-1.117310,0.234416,1.659802,0.742044
2,-0.191836,-0.887629,-0.747158,1.692455,0.050808,-0.636996,0.190915,2.100255,0.120159,0.617203,0.300170,-0.352250,-1.142518,-0.349343,-0.208894,0.586623,0.838983,0.931102,0.285587,0.885141
3,-0.754398,1.252868,0.512930,-0.298093,0.488518,-0.075572,1.131629,1.519817,2.185575,-1.396496,-1.444114,-0.504466,0.160037,0.876169,0.315635,-2.022201,-0.306204,0.827975,0.230095,0.762011
4,-0.222328,-0.200758,0.186561,0.410052,0.198300,0.119009,-0.670662,0.377564,0.121821,1.129484,1.198918,0.185156,-0.375285,-0.638730,0.423494,0.077340,-0.343854,0.043597,-0.620001,0.698032

In [5]:
X_star = X.copy()

In [6]:
X_star.iloc[:, -1] = X_star.iloc[:, 0] + np.random.normal(loc=0, scale=10**(-4), size=1000) #adding noise normally distributed with std = 0.0004
X_star.iloc[:, -2] = X_star.iloc[:, 0] + np.random.normal(loc=0, scale=10**(-4), size=1000) #adding noise normally distributed with std = 0.0004

print('X* (noise added)')
X_star.head()

X* (noise added)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,1.624345,-0.611756,-0.528172,-1.072969,0.865408,-2.301539,1.744812,-0.761207,0.319039,-0.249370,1.462108,-2.060141,-0.322417,-0.384054,1.133769,-1.099891,-0.172428,-0.877858,1.624399,1.624152
1,-1.100619,1.144724,0.901591,0.502494,0.900856,-0.683728,-0.122890,-0.935769,-0.267888,0.530355,-0.691661,-0.396754,-0.687173,-0.845206,-0.671246,-0.012665,-1.117310,0.234416,-1.100604,-1.100635
2,-0.191836,-0.887629,-0.747158,1.692455,0.050808,-0.636996,0.190915,2.100255,0.120159,0.617203,0.300170,-0.352250,-1.142518,-0.349343,-0.208894,0.586623,0.838983,0.931102,-0.192093,-0.191919
3,-0.754398,1.252868,0.512930,-0.298093,0.488518,-0.075572,1.131629,1.519817,2.185575,-1.396496,-1.444114,-0.504466,0.160037,0.876169,0.315635,-2.022201,-0.306204,0.827975,-0.754419,-0.754419
4,-0.222328,-0.200758,0.186561,0.410052,0.198300,0.119009,-0.670662,0.377564,0.121821,1.129484,1.198918,0.185156,-0.375285,-0.638730,0.423494,0.077340,-0.343854,0.043597,-0.222349,-0.222226

### c.	(4 points) Calculate the covariance matrix of X and X* (Sigma, Sigma*).

In [7]:
Sigma = X.cov()

print('Sigma')
Sigma.head()

Sigma

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,1.001497,-0.050416,-0.044215,0.029779,0.059878,-0.015669,0.016527,-0.027923,-0.011138,0.042200,0.012380,0.001198,0.028557,-0.016113,-0.010057,-0.009525,0.073987,0.005610,-0.005002,-0.001856
1,-0.050416,1.001197,-0.026004,-0.023351,-0.013000,-0.011935,-0.006069,-0.014928,0.035260,0.014396,0.060224,0.000022,0.053114,-0.038140,0.015328,0.007932,-0.012051,0.046309,0.035728,0.027696
2,-0.044215,-0.026004,1.019129,-0.057305,0.001869,0.008882,-0.029721,0.051896,-0.011045,0.029316,-0.005510,-0.037863,0.000846,0.031526,-0.028823,0.023011,-0.021775,0.009232,-0.037549,-0.039144
3,0.029779,-0.023351,-0.057305,0.945838,-0.087699,0.003917,0.006719,0.073963,-0.042114,0.021755,0.056051,0.047124,0.012325,0.013028,-0.063144,-0.029035,-0.007511,0.000621,-0.010949,0.017791
4,0.059878,-0.013000,0.001869,-0.087699,1.002807,-0.027833,0.018388,-0.011241,0.048572,0.016413,0.073225,0.016998,0.011222,-0.028815,0.007335,-0.023451,0.023647,0.048810,-0.026085,-0.060067

In [8]:
Sigma_star = X_star.cov()

print('Sigma*')
Sigma_star.head()

Sigma*

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,1.001497,-0.050416,-0.044215,0.029779,0.059878,-0.015669,0.016527,-0.027923,-0.011138,0.042200,0.012380,0.001198,0.028557,-0.016113,-0.010057,-0.009525,0.073987,0.005610,1.001492,1.001500
1,-0.050416,1.001197,-0.026004,-0.023351,-0.013000,-0.011935,-0.006069,-0.014928,0.035260,0.014396,0.060224,0.000022,0.053114,-0.038140,0.015328,0.007932,-0.012051,0.046309,-0.050416,-0.050417
2,-0.044215,-0.026004,1.019129,-0.057305,0.001869,0.008882,-0.029721,0.051896,-0.011045,0.029316,-0.005510,-0.037863,0.000846,0.031526,-0.028823,0.023011,-0.021775,0.009232,-0.044213,-0.044212
3,0.029779,-0.023351,-0.057305,0.945838,-0.087699,0.003917,0.006719,0.073963,-0.042114,0.021755,0.056051,0.047124,0.012325,0.013028,-0.063144,-0.029035,-0.007511,0.000621,0.029783,0.029775
4,0.059878,-0.013000,0.001869,-0.087699,1.002807,-0.027833,0.018388,-0.011241,0.048572,0.016413,0.073225,0.016998,0.011222,-0.028815,0.007335,-0.023451,0.023647,0.048810,0.059878,0.059874

### d.	(10 points) Shrink covariace matrix using OAS and Ledoit and Wolf.  Calculate the condition number after shrinkage.

In [9]:
oas1 = OAS().fit(Sigma)
cov_oas1 = oas1.covariance_
oas2 = OAS().fit(Sigma_star)
cov_oas2 = oas2.covariance_
cond_oas1 = np.linalg.cond(X)
cond_oas2 = np.linalg.cond(X_star)

lw1 = LedoitWolf().fit(Sigma)
cov_lw1 = lw1.covariance_
lw2 = LedoitWolf().fit(Sigma_star)
cov_lw2 = lw2.covariance_

cond_lw1 = np.linalg.cond(X)
cond_lw2 = np.linalg.cond(X_star)

print('Sigma')
print('OAS condition number for Sigma =', cond_oas1)
print('log(OAS cov condition number for Sigma) =',np.log(cond_oas1)) 
print('OAS condition number for Sigma* =', cond_oas2)
print('log(OAS cov condition number for Sigma*) =',np.log(cond_oas2)) 
print('\n')
print('Sigma*')
print('LedoitWolf condition number =', cond_lw1)
print('log(LedoitWolf cov condition number) =',np.log(cond_lw1))
print('LedoitWolf condition number =', cond_lw2)
print('log(LedoitWolf cov condition number) =',np.log(cond_lw2))

Sigma
OAS condition number for Sigma = 1.297037893937766
log(OAS cov condition number for Sigma) = 0.2600831215133436
OAS condition number for Sigma* = 30139.903245685866
log(OAS cov condition number for Sigma*) = 10.31360526201229


Sigma*
LedoitWolf condition number = 1.297037893937766
log(LedoitWolf cov condition number) = 0.2600831215133436
LedoitWolf condition number = 30139.903245685866
log(LedoitWolf cov condition number) = 10.31360526201229

### e.	(3 points) One sentence on the difference between the two.

#### Sigma* shows larger condition numbers from ledoitWolf method than those from OAS method and clearly larger condition numbers than Sigma, which is normally distributed without noise

# Problem #3

In [10]:
df = pd.read_csv('Data.csv', parse_dates=True, index_col='Date')
df.head()

,AGG,TLT,IEF,LQD,XLB,XLE,XLF,XLI,XLK,XLP,XLU,XLV,XLY,EFA,EWJ,EWW,EWY,EZU
Date,,,,,,,,,,,,,,,,,,
2017-09-18,109.860001,126.129997,107.269997,120.900002,56.380001,66.120003,25.059999,69.779999,58.790001,55.299999,54.189999,82.570000,89.320000,68.150002,55.250000,55.910000,69.839996,43.080002
2017-09-19,109.800003,125.820000,107.150002,120.970001,56.669998,66.389999,25.250000,69.849998,59.049999,55.130001,54.080002,81.919998,89.239998,68.470001,55.570000,55.650002,70.070000,43.290001
2017-09-20,109.709999,125.910004,106.940002,120.820000,56.869999,66.839996,25.400000,70.360001,58.810001,54.599998,53.680000,82.000000,89.540001,68.320000,55.590000,55.860001,69.699997,43.080002
2017-09-21,109.690002,125.839996,106.800003,120.820000,56.750000,66.860001,25.459999,70.570000,58.490002,54.080002,53.669998,81.580002,89.389999,68.180000,55.369999,55.730000,69.690002,43.110001
2017-09-22,109.769997,126.199997,106.989998,120.980003,56.549999,67.199997,25.430000,70.750000,58.520000,53.919998,53.230000,81.580002,89.540001,68.389999,55.430000,55.990002,69.330002,43.200001

### a.	(3 points) Calculate Daily Returns

In [11]:
df_return = df.pct_change(1)
df_return.dropna(inplace=True) #to drop the first row and NaN rows

In [12]:
print('3-a Daily returns with NaN dropped')
df_return.head()

3-a Daily returns with NaN dropped

,AGG,TLT,IEF,LQD,XLB,XLE,XLF,XLI,XLK,XLP,XLU,XLV,XLY,EFA,EWJ,EWW,EWY,EZU
Date,,,,,,,,,,,,,,,,,,
2017-09-19,-0.000546,-0.002458,-0.001119,0.000579,0.005144,0.004083,0.007582,0.001003,0.004422,-0.003074,-0.002030,-0.007872,-0.000896,0.004696,0.005792,-0.004650,0.003293,0.004875
2017-09-20,-0.000820,0.000715,-0.001960,-0.001240,0.003529,0.006778,0.005941,0.007301,-0.004064,-0.009614,-0.007396,0.000977,0.003362,-0.002191,0.000360,0.003774,-0.005280,-0.004851
2017-09-21,-0.000182,-0.000556,-0.001309,0.000000,-0.002110,0.000299,0.002362,0.002985,-0.005441,-0.009524,-0.000186,-0.005122,-0.001675,-0.002049,-0.003958,-0.002327,-0.000143,0.000696
2017-09-22,0.000729,0.002861,0.001779,0.001324,-0.003524,0.005085,-0.001178,0.002551,0.000513,-0.002959,-0.008198,0.000000,0.001678,0.003080,0.001084,0.004665,-0.005166,0.002088
2017-09-25,0.002369,0.006260,0.002991,0.003720,0.001768,0.014435,-0.001180,0.000000,-0.011791,0.007233,0.009205,-0.002942,-0.002122,-0.005703,0.002165,-0.007144,-0.006491,-0.010880

### b.	(3 points) Calculate covariance matrix

In [13]:
print("3-b Covariance Matrix")
cov_return = df_return.cov()
cov_return.head()

3-b Covariance Matrix

,AGG,TLT,IEF,LQD,XLB,XLE,XLF,XLI,XLK,XLP,XLU,XLV,XLY,EFA,EWJ,EWW,EWY,EZU
AGG,0.000003,0.000010,0.000005,4.401203e-06,-3.972285e-06,-5.087956e-06,-0.000008,-4.833951e-06,-0.000004,-3.758832e-08,0.000004,-0.000002,-0.000003,-0.000002,-0.000002,-8.044312e-07,-0.000002,-0.000003
TLT,0.000010,0.000041,0.000017,1.377137e-05,-2.241699e-05,-2.506013e-05,-0.000035,-2.680071e-05,-0.000024,-4.769238e-06,0.000012,-0.000015,-0.000021,-0.000016,-0.000016,-1.106116e-05,-0.000018,-0.000020
IEF,0.000005,0.000017,0.000008,5.861373e-06,-1.146686e-05,-1.285718e-05,-0.000017,-1.341662e-05,-0.000013,-2.833640e-06,0.000005,-0.000008,-0.000011,-0.000009,-0.000008,-6.510723e-06,-0.000010,-0.000010
LQD,0.000004,0.000014,0.000006,7.667735e-06,6.228948e-07,-7.062950e-07,-0.000004,3.606358e-07,0.000003,4.038339e-06,0.000007,0.000003,0.000002,0.000002,0.000002,3.838740e-06,0.000004,0.000001
XLB,-0.000004,-0.000022,-0.000011,6.228948e-07,1.190870e-04,9.229903e-05,0.000088,1.005781e-04,0.000104,4.889608e-05,0.000014,0.000071,0.000088,0.000069,0.000068,6.824527e-05,0.000094,0.000076

### c.	(3 points) Calculate condition number

In [14]:
cond_prior = np.linalg.cond(cov_return)

print('Sample covariance condition number =', cond_prior)
print('log(sample cov condition number) =',np.log(cond_prior))

Sample covariance condition number = 6084.011362592199
log(sample cov condition number) = 8.713419520996144

### d.	(3 points) Use OAS, calculate condition number

In [15]:
oas3 = OAS().fit(df_return)
cov_oas3 = oas3.covariance_
df_cov_oas = pd.DataFrame(data=cov_oas3, columns=cov_return.columns, index=cov_return.index)
cond_oas3 = np.linalg.cond(cov_oas3)
        
print('3-d OAS condition number =', cond_oas3)
print('3-d log(OAS cov condition number) =',np.log(cond_oas3))

3-d OAS condition number = 1089.1741249819522
3-d log(OAS cov condition number) = 6.993175004533175

In [16]:
df_cov_oas.head(10)

,AGG,TLT,IEF,LQD,XLB,XLE,XLF,XLI,XLK,XLP,XLU,XLV,XLY,EFA,EWJ,EWW,EWY,EZU
AGG,4.052891e-06,0.000010,0.000005,4.356249e-06,-3.931712e-06,-5.035988e-06,-0.000008,-4.784577e-06,-0.000003,-3.720439e-08,0.000004,-0.000002,-0.000003,-0.000002,-0.000002,-7.962148e-07,-0.000002,-0.000003
TLT,1.029455e-05,0.000042,0.000017,1.363071e-05,-2.218803e-05,-2.480416e-05,-0.000035,-2.652697e-05,-0.000024,-4.720525e-06,0.000011,-0.000015,-0.000021,-0.000016,-0.000015,-1.094818e-05,-0.000018,-0.000019
IEF,4.714647e-06,0.000017,0.000009,5.801505e-06,-1.134974e-05,-1.272586e-05,-0.000017,-1.327958e-05,-0.000013,-2.804697e-06,0.000005,-0.000008,-0.000011,-0.000009,-0.000008,-6.444223e-06,-0.000010,-0.000010
LQD,4.356249e-06,0.000014,0.000006,8.365049e-06,6.165326e-07,-6.990809e-07,-0.000004,3.569523e-07,0.000003,3.997091e-06,0.000007,0.000003,0.000002,0.000002,0.000002,3.799532e-06,0.000004,0.000001
XLB,-3.931712e-06,-0.000022,-0.000011,6.165326e-07,1.186462e-04,9.135629e-05,0.000087,9.955078e-05,0.000103,4.839666e-05,0.000013,0.000070,0.000087,0.000068,0.000068,6.754822e-05,0.000093,0.000075
XLE,-5.035988e-06,-0.000025,-0.000013,-6.990809e-07,9.135629e-05,1.591191e-04,0.000088,9.354637e-05,0.000100,3.970789e-05,0.000008,0.000069,0.000085,0.000067,0.000069,7.243628e-05,0.000084,0.000071
XLF,-7.716391e-06,-0.000035,-0.000017,-4.196533e-06,8.745704e-05,8.757601e-05,0.000122,9.554935e-05,0.000102,4.451969e-05,0.000008,0.000071,0.000087,0.000066,0.000067,5.753060e-05,0.000082,0.000072
XLI,-4.784577e-06,-0.000027,-0.000013,3.569523e-07,9.955078e-05,9.354637e-05,0.000096,1.167607e-04,0.000109,4.915288e-05,0.000014,0.000075,0.000092,0.000067,0.000068,6.424912e-05,0.000087,0.000073
XLK,-3.465472e-06,-0.000024,-0.000013,3.321252e-06,1.025943e-04,1.001784e-04,0.000102,1.088315e-04,0.000170,5.176819e-05,0.000017,0.000094,0.000119,0.000080,0.000082,7.606253e-05,0.000112,0.000086
XLP,-3.720439e-08,-0.000005,-0.000003,3.997091e-06,4.839666e-05,3.970789e-05,0.000045,4.915288e-05,0.000052,6.630384e-05,0.000036,0.000049,0.000047,0.000034,0.000036,3.636751e-05,0.000039,0.000034

### e.	(15 points) Agglomerative clustering

In [17]:
from sklearn.cluster import AgglomerativeClustering
from scipy.cluster.hierarchy import dendrogram, linkage
from scipy.spatial.distance import pdist, squareform

In [18]:
corr_return = df_return.corr()
corr_return.head()

,AGG,TLT,IEF,LQD,XLB,XLE,XLF,XLI,XLK,XLP,XLU,XLV,XLY,EFA,EWJ,EWW,EWY,EZU
AGG,1.000000,0.889511,0.924126,0.873480,-0.200043,-0.221070,-0.386926,-0.245407,-0.147329,-0.002539,0.251931,-0.115714,-0.170879,-0.166590,-0.131187,-0.031316,-0.079214,-0.198046
TLT,0.889511,1.000000,0.923838,0.773951,-0.319680,-0.308336,-0.490347,-0.385288,-0.285769,-0.091217,0.211789,-0.244051,-0.315683,-0.312935,-0.273456,-0.121936,-0.207383,-0.327178
IEF,0.924126,0.923838,1.000000,0.747263,-0.370954,-0.358859,-0.552532,-0.437543,-0.360540,-0.122944,0.217766,-0.297235,-0.370741,-0.377653,-0.328012,-0.162816,-0.258805,-0.394568
LQD,0.873480,0.773951,0.747263,1.000000,0.020613,-0.020166,-0.138279,0.012031,0.092785,0.179236,0.316318,0.096272,0.073261,0.078871,0.086348,0.098201,0.112451,0.039761
XLB,-0.200043,-0.319680,-0.370954,0.020613,1.000000,0.668707,0.731241,0.851414,0.727282,0.550679,0.146594,0.671205,0.760413,0.781330,0.710981,0.442997,0.651420,0.746081

In [19]:
dist = pdist(corr_return, metric='euclidean')
df_dist = pd.DataFrame(squareform(dist), columns=corr_return.columns, index=corr_return.index)
print('distance matrix -- distance from perfectly positive correlation (1)')
df_dist.head(10)

distance matrix -- distance from perfectly positive correlation (1)

,AGG,TLT,IEF,LQD,XLB,XLE,XLF,XLI,XLK,XLP,XLU,XLV,XLY,EFA,EWJ,EWW,EWY,EZU
AGG,0.000000,0.485349,0.668306,0.843102,3.977259,3.723103,4.127439,4.085480,3.914199,3.181660,1.963109,3.744222,3.980397,4.073133,3.875803,3.103309,3.595464,3.973831
TLT,0.485349,0.000000,0.231961,1.295040,4.324801,4.047054,4.446720,4.430793,4.269298,3.524013,2.239929,4.097538,4.334682,4.431633,4.231670,3.425715,3.945769,4.321508
IEF,0.668306,0.231961,0.000000,1.492571,4.499049,4.215878,4.613116,4.603869,4.446772,3.693555,2.385541,4.272729,4.510871,4.609877,4.408449,3.593645,4.121372,4.497163
LQD,0.843102,1.295040,1.492571,0.000000,3.258286,3.044360,3.447451,3.366825,3.185230,2.481856,1.478085,3.019133,3.251463,3.340079,3.150269,2.460796,2.888044,3.258367
XLB,3.977259,4.324801,4.499049,3.258286,0.000000,0.624590,0.542085,0.267451,0.438032,1.152135,2.496458,0.583540,0.384929,0.451922,0.467938,1.270269,0.695553,0.464150
XLE,3.723103,4.047054,4.215878,3.044360,0.624590,0.000000,0.685671,0.657993,0.700385,1.136943,2.285148,0.746308,0.690649,0.782314,0.683322,1.075038,0.769857,0.715928
XLF,4.127439,4.446720,4.613116,3.447451,0.542085,0.685671,0.000000,0.433765,0.629950,1.308790,2.599801,0.749135,0.576736,0.680935,0.681376,1.390555,0.910837,0.633247
XLI,4.085480,4.430793,4.603869,3.366825,0.267451,0.657993,0.433765,0.000000,0.415462,1.215538,2.577654,0.582682,0.336440,0.500078,0.528969,1.371383,0.813630,0.534843
XLK,3.914199,4.269298,4.446772,3.185230,0.438032,0.700385,0.629950,0.415462,0.000000,1.147116,2.453666,0.467888,0.214820,0.502253,0.471746,1.270123,0.678424,0.532295
XLP,3.181660,3.524013,3.693555,2.481856,1.152135,1.136943,1.308790,1.215538,1.147116,0.000000,1.539124,0.847049,1.157860,1.318088,1.152813,1.128222,1.137163,1.277250

In [20]:
cls=linkage(dist, method='single', metric='euclidean')

In [21]:
print('Agglomerative clustering')
cls

Agglomerative clustering

array([[ 8.        , 12.        ,  0.21482012,  2.        ],
       [13.        , 17.        ,  0.21768672,  2.        ],
       [ 1.        ,  2.        ,  0.23196055,  2.        ],
       [ 4.        ,  7.        ,  0.2674509 ,  2.        ],
       [14.        , 19.        ,  0.31642197,  3.        ],
       [18.        , 21.        ,  0.33643952,  4.        ],
       [ 6.        , 23.        ,  0.43376477,  5.        ],
       [22.        , 24.        ,  0.45192241,  8.        ],
       [11.        , 25.        ,  0.46788769,  9.        ],
       [ 0.        , 20.        ,  0.48534907,  3.        ],
       [16.        , 26.        ,  0.55318661, 10.        ],
       [ 5.        , 28.        ,  0.62458972, 11.        ],
       [ 3.        , 27.        ,  0.84310151,  4.        ],
       [ 9.        , 29.        ,  0.84704876, 12.        ],
       [15.        , 31.        ,  0.9309697 , 13.        ],
       [10.        , 30.        ,  1.47808545,  5.        ],
       [32.        , 33.        ,  1.53912363, 18.        ]])

### f.	(8 points) Plot Dendrogram – describe the different clusters.

In [22]:
import matplotlib.pyplot as plt
import pylab

plt.figure(figsize=(35,15))
labelsize=40
ticksize=30

plt.title('Hierarchical Clustering Dendrogram', fontsize=30)
plt.xlabel('Stock', fontsize=labelsize)
plt.ylabel('Distance', fontsize=labelsize)

dendr=dendrogram(cls, labels=df_dist.columns)
plt.tight_layout()
plt.ylabel('Euclidean Distance')
pylab.yticks(fontsize=ticksize)
pylab.xticks(fontsize=ticksize)
plt.show()

#### Distance (single linkage) gets smaller as the correlation between stocks is close to 1 (nodes in the lower tree)

### g.	(15 points) Get HRP weights

In [23]:
import scipy.cluster.hierarchy as sch

In [24]:
cov_hrp = pd.DataFrame(cov_return.values)
corr_hrp = pd.DataFrame(corr_return.values)

In [25]:
def correlDist(corr):
    # A distance matrix based on correlation, where 0<=d[i,j]<=1
    # This is a proper distance metric
    dist = ((1 - corr) / 2.)**.5  # distance matrix
    return dist

In [26]:
def getIVP(cov, **kargs):
    ivp = 1. / np.diag(cov)
    ivp /= ivp.sum()
    return ivp

In [27]:
def getClusterVar(cov,cItems):
    cov_=cov.loc[cItems,cItems] 
    w_=getIVP(cov_).reshape(-1,1)
    cVar=np.dot(np.dot(w_.T,cov_),w_)[0,0]
    return cVar

In [28]:
def getQuasiDiag(link):
    link = link.astype(int)
    sortIx = pd.Series([link[-1, 0], link[-1, 1]])
    numItems = link[-1, 3]  
    while sortIx.max() >= numItems:
        sortIx.index = range(0, sortIx.shape[0] * 2, 2)  
        df0 = sortIx[sortIx >= numItems]  
        i = df0.index
        j = df0.values - numItems
        sortIx[i] = link[j, 0]  
        df0 = pd.Series(link[j, 1], index=i + 1)
        sortIx = sortIx.append(df0)  
        sortIx = sortIx.sort_index()  
        sortIx.index = range(sortIx.shape[0])  

    return sortIx.tolist()

In [29]:
def getRecBipart(cov, sortIx):
    w = pd.Series(1, index=sortIx)
    cItems = [sortIx]  
    while len(cItems) > 0:
        cItems = [i[j:k] for i in cItems for j, k in ((0, int(len(i) / 2)), (int(len(i) / 2), len(i))) if len(i) > 1]  
        for i in range(0, len(cItems), 2):  
            cItems0 = cItems[i]  
            cItems1 = cItems[i + 1]  
            cVar0 = getClusterVar(cov, cItems0)
            cVar1 = getClusterVar(cov, cItems1)
            alpha = 1 - cVar0 / (cVar0 + cVar1)
            w[cItems0] *= alpha  
            w[cItems1] *= 1 - alpha  
    return w

In [30]:
def getHRP(cov, corr):
    corr, cov = pd.DataFrame(corr), pd.DataFrame(cov)
    dist = correlDist(corr)
    link = sch.linkage(dist, 'single')
    sortIx = getQuasiDiag(link)
    sortIx = corr.index[sortIx].tolist()
    
    hrp = getRecBipart(cov, sortIx)

    return hrp.sort_index()

In [31]:
w_hrp = getHRP(cov_hrp, corr_hrp)
df_w_hrp = pd.DataFrame(index=df_return.columns, columns=['hrp weight'], data=w_hrp.values)

C:\Users\alee8\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: ClusterWarning: scipy.cluster: The symmetric non-negative hollow observation matrix looks suspiciously like an uncondensed distance matrix
  after removing the cwd from sys.path.

In [32]:
df_w_hrp

     hrp weight
AGG    0.431040
TLT    0.037026
IEF    0.190538
LQD    0.186131
XLB    0.003220
XLE    0.007967
XLF    0.006228
XLI    0.003272
XLK    0.004477
XLP    0.028969
XLU    0.037127
XLV    0.008508
XLY    0.006370
EFA    0.010560
EWJ    0.008848
EWW    0.013448
EWY    0.007237
EZU    0.009033

In [33]:
sum(df_w_hrp.iloc[:,0])

1.0000000000000002